### ISSUE TITLE
Package the dasbus library for Debian

### ISSUE THREAD

**Issue by poncovka** [rhinstaller/dasbus#50]
It would be great to get dasbus on Debian.

[0] https://wiki.debian.org/Packaging
[1] https://www.debian.org/doc/manuals/maint-guide/

**Comment by seahawk1986** [comment]
Hello,
after watching your talk at DevConf.cz 2020 recently, I built a debian package for Ubuntu 20.04 as a preparation for porting some programs from pydbus to dasbus (using the source package for pydbus as a template) in https://launchpad.net/~seahawk1986-hotmail/+archive/ubuntu/experimental-main/+packages?field.name_filter=dasbus&field.status_filter=published&field.series_filter=

Maybe this can give you a starting point to get to a proper Debian package (which seems to be quite a lengthy process: https://www.debian.org/doc/manuals/developers-reference/pkgs.de.html#new-packages).

I had to add two patches to adapt the doc build scripts to the program name and sphinx version used in Ubuntu 20.04:
````diff
Index: dasbus-1.4.18+git20210419-g9672512-9672512/docs/Makefile
===================================================================
--- dasbus-1.4.18+git20210419-g9672512-9672512.orig/docs/Makefile       2021-04-19 00:44:41.000000000 +0200
+++ dasbus-1.4.18+git20210419-g9672512-9672512/docs/Makefile    2021-04-29 13:21:28.291449725 +0200
@@ -14,7 +14,7 @@

 # Generate the API documentation.
 api:
-       sphinx-apidoc-3 --separate -o api ../dasbus
+       sphinx-apidoc --separate -o api ../dasbus

 .PHONY: help api Makefile
````
And because of the old sphinx version (1.8.5) in Ubuntu 20.04 (Debian up to Version 10 (buster) has the same issue - this change is not needed for Ubuntu 20.10, Debian 11 (bullseye) or later versions, which provide a sphinx version 3.x where `master_doc` aka `root_doc` already defaults to `'index'`):
````diff
Index: dasbus-1.4.18+git20210419-g9672512-9672512/docs/conf.py
===================================================================
--- dasbus-1.4.18+git20210419-g9672512-9672512.orig/docs/conf.py        2021-04-19 00:44:41.000000000 +0200
+++ dasbus-1.4.18+git20210419-g9672512-9672512/docs/conf.py     2021-04-29 16:38:41.823203297 +0200
@@ -40,6 +40,9 @@
     'sphinx_rtd_theme',
 ]

+# set the master doc
+master_doc = 'index'
+
 # Add any paths that contain templates here, relative to this directory.
 templates_path = ['_templates']

````

**Comment by poncovka** [comment]
This is great! Thanks for the pointers!

**Comment by bluca** [comment]
Uploaded, will be in Debian and Ubuntu once approved by the archive team https://ftp-master.debian.org/new/dasbus_1.6-1.html

**Comment by jkonecny12** [comment]
This is great. Thank a lot for helping here!

**Comment by bluca** [comment]
It has now been approved, so this issue can be closed: https://tracker.debian.org/pkg/dasbus

**Comment by poncovka** [comment]
That's amazing! Thank you for your work :-)
