### ISSUE TITLE
Are multiple output arguments possible with dasbus?

### ISSUE THREAD

**Issue by seahawk1986** [rhinstaller/dasbus#60]
Hello,

in my DBus-API currently implemented with pydbus (and previously python-dbus) I am often returning multiple output values in signals and methods, e.g.
```xml
<node>
   <interface name="de.test.my.Interface">
       <method name="GetMultipleReturnValues">
            <arg direction="out" type="s" name="out1"/>
            <arg direction="out" type="s" name="out2"/>
       </method>
   </interface>
</node>
```

Is there a way to do this in dasbus?

Returning a Tuple like in
```python
@dbus_signal("de.test.my.Interface")
class ControllerInterface(object):
    def GetMultipleReturnValues(self) -> Tuple[Str, Str]:
        return "foo", "bar"
````
would create a single out argument with the type `(ss)`.

If I set `__dbus_xml__` by hand:
```python
class ControllerInterface:
    __dbus_xml__ = """
        <node>
            <interface name="de.test.my.Interface">
                <method name="GetMultipleReturnValues">
                    <arg direction="out" type="s" name="out1"/>
                    <arg direction="out" type="s" name="out2"/>
                </method>
            </interface>
        </node>
    """
    def GetMultipleReturnValues(self) -> Tuple[Str, Str]:
        return "foo", "bar"
```
dasbus can't handle the output: `TypeError: Tuple mismatches value's number of elements (ss) (('foo', 'bar'),)`

Also if a class is decorated with `@dbus_interface`, only methods which begin with an uppercase letter and only contain alphanumeric characters are added to the generated interface definition (this seems to be caused by https://github.com/rhinstaller/dasbus/blob/b04cdcdcdee9c1aaad6864f99ebf74e7a7933b3b/dasbus/server/interface.py#L264 ), which enforces more limits than the dbus specification for [Member names
](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names-member) (wich would allow snake_case names), but does not check for the [maximum allowed name length of 255 characters](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names) (a method with a name longer than 255 characters will show up in programs in the interface definition, but can't be called) - it would be helpful to mention this limitation in den Documentation, if this is intentional.

**Comment by poncovka** [comment]
Hello,

the `@dbus_interface` decorator doesn't support multiple output arguments of DBus methods. I will have to think it through, but I am not sure if I want to support it. The decorator is more like a best-effort tool for a quick development of DBus API. It is not supposed to handle every use case. However, the solution with `__dbus_xml__` should work. I will look at it and fix it during the next week.

The pattern for member names is based on a convention and it seems to be a good practice. It could be dangerous to generate the DBus interface from all members of the class, because some of them might not be intended as members of DBus API. With the current restrictions, it is more difficult to make this mistake. You can always use `__dbus_xml__` or override the `DBusSpecificationGenerator` class. Anyway, it should be definitely documented.

Thanks for the report!

**Comment by poncovka** [comment]
The issue should be resolved with: https://github.com/rhinstaller/dasbus/pull/61

**Comment by poncovka** [comment]
The documentation issues should be resolved with: https://github.com/rhinstaller/dasbus/pull/63

**Comment by poncovka** [comment]
I have considered to add a check for the maximum name length, but it is very unlikely that someone will exceed it. The Python code would be unreadable and it would violate [all kinds of conventions](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). Therefore, I am closing this issue.
